version: "3.3"

networks:
  my-network:
    driver: bridge

services:
  mongodb_container:
    image: mongo:latest
    container_name: mongodb_restapi
    environment:
      MONGO_INITDB_ROOT_USERNAME: node_user
      MONGO_INITDB_ROOT_PASSWORD: node_user
      MONGO_INITDB_DATABASE: node_webapp
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - my-network
## if you use a named volume, you must also define it here.
volumes:
  db_data:
  mongodb_data_container: